apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: jenkins-app
          image: gcr.io/path-to-jenkins-image
          ports:
            - containerPort: 8080
              protocol: TCP
